### ISSUE TITLE
Document how to get a working local setup

### ISSUE THREAD

**Issue by yonatan-reicher** [TekClinic/TekClinic-Web-App#58]
There is setup.md but it is out of date and does not detail everything.

Main problem: Need a file called .env.local
and need to figure out what to put in it

API_URL
NEXT_PUBLIC_API_URL
NEXT_PUBLIC_SYNCFUSION_LICENSE_KEY

**Comment by yonatan-reicher** [comment]
Should `NEXT_PUBLIC_SYNCFUSION_LICENSE_KEY` be non-`NEXT_PUBLIC`?

NEXT_PUBLIC values are inlined, is that leaking our secret key?

**Comment by UriKH** [comment]
We think we figured out `NEXT_PUBLIC_API_URL` `NEXT_PUBLIC_SYNCFUSION_LICENSE_KEY`.

Now encountered  `KEYCLOAK_CLIENT_ID` not fount.

Is it a local key we should be able to generate by ourselves somehow or is it also a specific value?

**Comment by UriKH** [comment]
All fixed but need to configure new:
- `KEYCLOAK_CLIENT_SECRET`
- `NEXTAUTH_SECRET`

**Comment by UriKH** [comment]
Issue fixed. Local setup working.
Need to:
* write script for fast local setup
* write usage instructions

**Comment by yonatan-reicher** [comment]
Ask someone if you are looking for .env.local file
